### ISSUE TITLE
Unable to create ObjectId before insertion

### ISSUE THREAD

**Issue by leopoldjoy** [hectorcorrea/mongoConnect#1]
@hectorcorrea I am used to the following code:

    var MongoClient = require('mongodb').MongoClient;
    MongoClient.connect(myurl, function (err, db) {
      const groupId = MongoClient.ObjectID;
      db.colllection('groups').insert({
        {
           _id: groupId,
           name: 'my test'
        }
      });
    });

How can I create an ObjectId before hand using `mongoConnect`?

**Comment by leopoldjoy** [comment]
I found [bson-objectid](https://github.com/williamkapke/bson-objectid) which enables you to create an ObjectId() beforehand.

**Comment by hectorcorrea** [comment]
@leopoldjoy I am glad you figure it out!
